arkit checkpoint

diff --git a/arkit b/arkit
--- a/arkit
+++ b/arkit
@@ -2,14 +2,17 @@
 
 set -u			# treat unset variables as an error when substituting
 me=$( basename $0 )
+
 repo=archive.org
 resolver=n2t.net
 publisher='California Digital Library'
 collection=luck
-ezcreds=		# ezid credentials
-force=			# init flag
-test=			# init flag
-iso8601format='+%Y-%m-%dT%H:%M:%S%z'	# date format
+iso8601format='+%Y-%m-%dT%H:%M:%S%z'		# date format
+cc0url='https://creativecommons.org/publicdomain/zero/1.0/'
+ezcreds=					# ezid credentials
+force=						# init flag
+noexec=						# init flag
+test=						# init flag
 
 summary="
     $me init [--force] [--test] File 'Creator|Title|Date' ['Subject[|...]']
@@ -64,6 +67,36 @@ function ark2iaid {
 	sed -e 's,^ark:/*,ark_,' -e 's,/,_,g' <<< $ark
 }
 
+function delete_ark {
+
+	local ark=${1:-}
+	[[ ! "$ark" ]] && {
+		echo Error: no ARK specified 1>&2
+		return 1
+	}
+	echo -n "Removing ARK $ark: "
+	ezcl p "$ezcreds" delete $ark || {
+		echo Error: failed to delete $ark 1>&2
+		return 1
+	}
+	return 0
+}
+
+function delete_iaid {		# delete Internet Archive id
+
+	local iaid=${1:-}
+	[[ ! "$iaid" ]] && {
+		echo Error: no IAID specified 1>&2
+		return 1
+	}
+	echo -n "Removing IA object $iaid: "
+	ia delete $iaid --all || {
+		echo "Error: failed to delete $iaid files" 1>&2
+		return 1
+	}
+	return 0
+}
+
 function arkit_init {
 
 	while [[ "$1" =~ ^- ]]
@@ -71,6 +104,7 @@ function arkit_init {
 		case $1 in
 		--force|-f)	force=1 ;;
 		--test|-t)	test=1 ;;
+		--noexec|-n)	noexec='+' ;;	# boolean/sigil
 		*)
 			echo "Error: unknown option $1" 1>&2
 			return 1
@@ -98,12 +132,14 @@ function arkit_init {
 		usage 1>&2
 		return 1
 	}
-	local ifs_saved="$IFS"
-	IFS='|'
-		# yyy should probably untaint $Meta and $Subjects
-		read -a erc <<< $Meta
-		read -a keywords <<< $Subjects
-	IFS="$ifs_saved"
+	#local ifs_saved="$IFS"
+	# yyy should probably untaint $Meta and $Subjects
+	# IFS set for duration of extended (cont. lines) command
+	IFS='|' \
+		read -a erc <<< $Meta; \
+		read -a keywords <<< $Subjects \
+	; # IFS value restored at end of command
+	#IFS="$ifs_saved"
 	local who=${erc[0]:-'(:unav)'}
 	local what=${erc[1]:-'(:unav)'}
 	local when=${erc[2]:-$File_date}
@@ -126,39 +162,67 @@ function arkit_init {
 	}
 	# reserved status allows us to delete the ARK if later we need to abort
 	local idstatus=reserved
-local ark=ark:/99999/fk4p275p26
-#	local ark=$( ezcl p "$ezcreds" mint $ezshoulder _status $idstatus |
-#		sed -n 's/^success: *//p' )
+	local ark
+	if [[ "$noexec" ]]
+	then
+		echo $noexec ezcl p "$ezcreds" \
+			mint $ezshoulder _status $idstatus
+		#ark=ark:/99999/fk4p275p26	# dummy to tide us over
+		ark=ark:/99999/fk4_noexec	# dummy to tide us over
+	else
+		ark=$( ezcl p "$ezcreds" mint $ezshoulder _status $idstatus | 
+			sed -n 's/^success: *//p' )
+	fi
 	[[ ! "$ark" ]] && {
 		echo Error: failed to create ARK 1>&2
 		return 1
 	}
+	echo $noexec Created new ARK id: $ark
 	local iaid=$( ark2iaid $ark )	# derive IA identifier from $ark
 	local landing="https://$repo/download/$iaid"
 	local redirect="$landing/$File"
 
+	local cmd
+	read -r -d '' cmd << EOT
 	ezcl p "$ezcreds" update $ark \
-			erc.who "$who" erc.what "$what" erc.when "$when" \
-			_target "$redirect" bestest "$redirect" \
-			landing "$landing" plunging "$redirect" \
-			> /dev/null || {
-		echo Error: failed to add metadata to new ARK: $ark 1>&2
-		echo -n "Removing ARK: "
-		ezcl p "$ezcreds" delete $ark
-		return 1
-	}
+		erc.who "$who" erc.what "$what" erc.when "$when" \
+		_target "$redirect" bestest "$redirect" \
+		landing "$landing" plunging "$redirect" \
 
-	echo Marking up new ARK identifier at EZID:
-	ezcl p "$ezcreds" view $ark | sed 's/^/    /'
+EOT
+	echo $noexec Initializing ARK metadata at EZID
+	if [[ "$noexec" ]]
+	then
+		echo $noexec $cmd
+	else
+		eval "$cmd" > /dev/null || {
+			echo Error: failed to add metadata to new ARK: $ark 1>&2
+			delete_ark $ark
+			return
+		}
+	fi
 
-#	local exists_at_ia=$( ia list $iaid )
+	echo $noexec Marking up ARK at EZID:
+	if [[ "$noexec" ]]
+	then
+		echo $noexec ezcl p "$ezcreds" view $ark
+	else
+		ezcl p "$ezcreds" view $ark | sed 's/^/    /'
+	fi
+
+	echo $noexec Checking existence at $repo
 	local exists_at_ia=
+	if [[ "$noexec" ]]
+	then
+		echo $noexec ia list $iaid
+	else
+		exists_at_ia=$( ia list $iaid )
+	fi
 	[[ "$exists_at_ia" ]] && {	# if it exists, start with clean slate
 		echo Removing $repo object files
-		ia delete $iaid --all || {
+		delete_iaid $iaid || {
 			echo "Error: failed to delete $iaid files" 1>&2
-			echo -n "Removing ARK: "
-			ezcl p "$ezcreds" delete $ark
+			delete_ark $ark
 			return 1
 		}
 	}
@@ -177,29 +241,49 @@ local ark=ark:/99999/fk4p275p26
 	--metadata="identifier-ark:https://$resolver/$ark"
 	--metadata="iaid:$iaid"
 	--metadata="collection:$collection"
-	--metadata="licenseurl:https://creativecommons.org/publicdomain/zero/1.0/"
+	--metadata="licenseurl:$cc0url"
 	--metadata="bestest:https://$resolver/$ark"
 	--metadata="landing:$landing"
 	--metadata="plunging:$redirect"
 	--metadata="highest_version:0"
 EOT
 	# this next line seems to be needed to get a final \n (bash bug?)
-	overall_metadata+="
-"
+	overall_metadata+=$'\n'
 	local keyword			# add keyword metadata
 	for keyword in "${keywords[@]}"
 	do
 		[[ ! "$keyword" ]] &&	# skipping blank keywords
 			continue
-		overall_metadata+="        --metadata=\"subject:$keyword\"
-"
+		overall_metadata+=" --metadata=\"subject:$keyword\"$'\n'
 	done
-	overall_metadata+="# === end overall object metadata
-"
-	echo "$overall_metadata" > $objfile
-	echo -n "Uploading stub object $ark ($iaid): "
-	echo ia upload $iaid - <<< stub --remote-name="$File" \
-		$( perl -ne '/^\s*#/ or chomp(), print' < $objfile )
+	overall_metadata+="# === end overall object metadata$'\n'
+	local ia_mdata_args=
+
+	if [[ "$noexec" ]]
+	then
+		echo $noexec writing metadata to $objfile:
+		echo "$overall_metadata"
+		echo $noexec ia upload $iaid - <<< stub --remote-name="$File" \
+			"$( perl -ne '/^\s*#/ or chomp(), print' < $objfile )"
+	else
+		echo "$overall_metadata" > $objfile
+		echo -n "Uploading stub object $ark ($iaid): "
+		IFS=$'\n' read -d '' -a ia_mdata_args \
+			<<< "$( perl -ne '/^\s*#/ or print' < arkit.t.yaml )"
+		# IFS will have reverted after one-time change
+
+		#showargs "${ia_mdata_args[@]}"
+		#showargs ia upload $iaid - <<< stub --remote-name="$File" 
+		#ia --debug upload $iaid $File "${ia_mdata_args[@]}" || {
+		#ia --debug upload $iaid $File "${ia_mdata_args[@]}"
+		eval "ia --debug upload $iaid $File $( perl -ne '/^\s*#/ or print' < arkit.t.yaml )"
+		local st=$?
+		[[ "$st" != 0 ]] && {
+			echo st is $st
+			echo "Error: failed to upload metadata for $iaid" 1>&2
+			delete_ark $ark
+		}
+	fi
 
 exit
 
