fixed rollout to handle new binder name scheme

diff --git a/ec2_bootmake b/ec2_bootmake
--- a/ec2_bootmake
+++ b/ec2_bootmake
@@ -45,10 +45,8 @@ and follow the instructions that follow and those that it prints, including:
 
         scp -p n2t-dev.n2t.net:warts/.pswdfile.n2t ~/warts/
 
-  4.  Make sure that your system people have (a) put your web server certs
-      file into the ~/ssl/ directory, (b) added mongodb.repo to
-      /etc/yum.repos.d, and (c) opened up access between mongo replicas on
-      ports 27017-27027 and 47017-47027.
+  4.  Make sure that your system people have put your web server certs
+      file into the ~/ssl/ directory.
 
   5.  Per the cert filename assignments in ~/$envsh, copy the correct
       files from ~/ssl/... into ~/warts/ssl.
@@ -59,16 +57,18 @@ Then run
       $0 build
 
 Finally have your system people install ~/n2t_create/n2t.service with
-systemd so that the service comes up and shuts down properly during
-system reboots. This involves asking them to turn off the mongod that
-systemd is configured to start up by default.
-
-      \$ sudo systemctl disable mongod
-
-You'll also want to have web service
-monitoring set up, eg, Nagios.
+systemd so that the service comes up and shuts down properly during system
+reboots.  You'll also want to have web service monitoring set up, eg, Nagios.
 
 EOT
+      #(b) added mongodb.repo to
+      #/etc/yum.repos.d, and (c) opened up access between mongo replicas on
+      #ports 27017-27027 and 47017-47027.
+#This involves asking them to turn off the mongod that
+#$systemd is configured to start up by default.
+#
+#     \$ sudo systemctl disable mongod
+
 	exit
 fi
 
@@ -172,25 +172,27 @@ export EGNAPA_SSL_CHAINFILE=/apps/n2t/warts/ssl/n2t_net.int-root
 # Define email address to receive system notifications, eg, from crontab.
 export EGNAPA_MAILTO='$mailto'
 
-# Define fully qualified hostname (don't trust hostname -f on some networks).
-export MG_HOST=\$EGNAPA_HOST
-
-# Define the hostports of the mongod daemons that should start up.
-export MG_LOCAL_DAEMONS="\$MG_HOST:27017,\$MG_HOST:27018,\$MG_HOST:27019"
-
-# Define connection string hosts, which may include non-local servers.
-# If undefined, this var defaults to MG_LOCAL_DAEMONS.
-export MG_CSTRING_HOSTS="\$MG_LOCAL_DAEMONS"
-
-# Define default mongo replica set options for the connection string.
-export MG_REPSETOPTS="socketTimeoutMS=30000&readPreference=primaryPreferred"
-
-# Define default mongo replica set name for the connection string.
-export MG_REPSETNAME="live"
-
-# Define default starter port (in a series) for replica set testing.
-export MG_TEST_PORT="47017"
 EOT
+
+## Define fully qualified hostname (don't trust hostname -f on some networks).
+#export MG_HOST=\$EGNAPA_HOST
+#
+## Define the hostports of the mongod daemons that should start up.
+#export MG_LOCAL_DAEMONS="\$MG_HOST:27017,\$MG_HOST:27018,\$MG_HOST:27019"
+#
+## Define connection string hosts, which may include non-local servers.
+## If undefined, this var defaults to MG_LOCAL_DAEMONS.
+#export MG_CSTRING_HOSTS="\$MG_LOCAL_DAEMONS"
+#
+## Define default mongo replica set options for the connection string.
+#export MG_REPSETOPTS="socketTimeoutMS=30000&readPreference=primaryPreferred"
+#
+## Define default mongo replica set name for the connection string.
+#export MG_REPSETNAME="live"
+#
+## Define default starter port (in a series) for replica set testing.
+#export MG_TEST_PORT="47017"
+
 		echo Created $envsh -- now you must copy your cert, keyfile, \
 			and chainfile to warts/ssl/n2t_net.{crt,key,int-root}
 	}
@@ -201,6 +203,8 @@ EOT
 # since we'll overwrite most inherited configuration. However, these
 # snapshot copies we make here will be incorporated over and over
 # when the n2t/eggnog instance is rebuilt (very frequent operation).
+
+# XXX after system patch, check for new files and re-snapshot!!
 
 function do_apache_httpd24 {
 
@@ -326,7 +330,7 @@ grep "^cdl.username.*$fakeuser" $hgrc && {
 #No packages in any requested group available to install or update
 
 	sudo yum -y install libdb4	# version 4 (v5 is default)
-	sudo yum -y install hg
+	sudo yum -y install hg git
 	sudo yum -y install 'perl(DB_File)'	# xxx drop this soon
 	sudo yum -y install 'perl(BerkeleyDB)'
 	sudo yum -y install 'perl(Data::UUID)' 'perl(Test::More)'
@@ -344,19 +348,20 @@ grep "^cdl.username.*$fakeuser" $hgrc && {
 	sudo yum -y install jq			# for Internet Archive API
 	sudo yum -y install golang		# nice, but not essential
 	sudo amazon-linux-extras install -y vim	# nice, but not essential
+	sudo amazon-linux-extras install postgresql11
 
-	sudo yum -y install mongodb-org
-	echo \
-"WARNING: on AWS Linux2, this installation of mongodb configures host boot
-scripts via systemd to automatically start mongo on port 27017" 1>&2
+	#sudo yum -y install mongodb-org
+	#echo \
+#"WARNING: on AWS Linux2, this installation of mongodb configures host boot
+#scripts via systemd to automatically start mongo on port 27017" 1>&2
 	# on mac, need: brew install mongodb --with-openssl
 	# yyy never actually used telnet for this
-	sudo yum -y install telnet	# network testing, eg, mongo replication
-	rpm -V mongodb-org || {		# because it has gpgcheck disabled
-		sudo yum -y remove mongodb-org
-		echo error: mongodb-org installation failed to verify -- aborting.
-		exit 1
-	}
+	#sudo yum -y install telnet	# network testing, eg, mongo replication
+	#rpm -V mongodb-org || {		# because it has gpgcheck disabled
+	#	sudo yum -y remove mongodb-org
+	#	echo error: mongodb-org installation failed to verify -- aborting.
+	#	exit 1
+	#}
 
 	# Try the hypothesis that we don't need these next two yum installs
 	# # XXX should confirm that these next are still needed
@@ -417,7 +422,8 @@ scripts via systemd to automatically start mongo on port 27017" 1>&2
 	# XXXX resume script here
 	#./make_instance build mongodb_pm httpd n2t > berrs 2>&1
 	# NB: ./make_instance requires "svu new", where installs go
-	./make_instance build mongodb_pm n2t > berrs 2>&1 || {
+	#./make_instance build mongodb_pm n2t > berrs 2>&1 || {
+	./make_instance build n2t > berrs 2>&1 || {
 		echo make_instance error -- bailing
 		svu cur
 		exit 1
