checkpoint 1

diff --git a/ec2_bootmake b/ec2_bootmake
--- a/ec2_bootmake
+++ b/ec2_bootmake
@@ -1,22 +1,23 @@
 #!/usr/bin/env bash
 
-# xxx use EGNAPA_SSL_{CERT,KEY,CHAIN}FILE if you want non-self-signed certs
+source ~/.bashrc	# which might not exist yet
 
-set -u		# make the use of unset variables throw an error
+set -u			# now make the use of unset variables throw an error
 hgrc=~/.hgrc
 envsh=warts/env.sh
 fakeuser=samsmith
 
 cmd=${1:-}
-if [[ "$cmd" != init && "$cmd" != build ]]
+if [[ "$cmd" != init && "$cmd" != build && "$cmd" != httpd ]]
 then
 	cat << EOT
 Usage: $0 [ init | build ]
 
-Use these instructions and script to set up N2T on a new AWS EC2 instance.
+Use these instructions and script to set up N2T on a new AWS EC2 instance
+(SSD and xfs recommended).
 Start by assuming the identity of the user (eg, sudo to a role account login)
 that you intend will administer the service and change to its home directory.
-Roughly, there are three steps: "init", configuration, and "build".
+Roughly, there are two steps: "init" and "build".
 
 Set up yum installation and other foundation files, by running (interactively,
 not backgrounding)
@@ -52,12 +53,8 @@ and follow the instructions that follow and those that it prints, including:
   5.  Per the cert filename assignments in ~/$envsh, copy the correct
       files from ~/ssl/... into ~/warts/ssl.
 
-Now do some basic configuration by running
 
-      source ~/.bashrc
-      svu new
-
-and then by running
+Then run
 
       $0 build
 
@@ -194,6 +191,46 @@ EOT
 	return 0
 }
 
+# All we need to do is the minimum to bring up Apache successfully,
+# since we'll overwrite most inherited configuration.
+
+function do_apache_httpd24 {
+
+	# ! assumes svu cur
+	local sysap=/etc/httpd		# system apache
+	local aptop=~/sv/cur/apache2
+	rm -fr $aptop
+	mkdir $aptop
+	cd $aptop
+	mkdir bin cgi-bin conf conf.d htdocs httpauth logs var var/run var/lock
+	ln -s /usr/sbin/httpd bin/httpd			# yyy needed?
+	ln -s $sysap/modules modules
+	ln -s $sysap/conf/magic conf/magic		# seem to be empty
+	ln -s $sysap/conf.modules.d conf.modules.d	# keep these verbatim,
+		# eg, /etc/httpd/conf.modules.d/00-base.conf; later we'll
+		# override selectively via build_server_tree, eg, 00-ssl.conf
+	cp /etc/httpd/conf.d/* conf.d	# later build_server_tree removes these
+	cp /etc/httpd/conf/httpd.conf conf/httpd.conf.sys	# one-time save
+	perl -pE '/^(Server|Document)Root/ and s/^/#/;
+		/^Listen/ and s/.*/Listen 18880/' conf/httpd.conf.sys \
+		> conf/httpd.conf
+	cat >> conf/httpd.conf << EOT
+
+PidFile $aptop/var/run/httpd.pid
+DefaultRuntimeDir $aptop/var/run
+EOT
+	rm  conf.d/ssl.conf		# disable SSL stuff for now
+	#cp conf.d/ssl.conf conf.d/ssl.conf.sys
+	#perl -pE '/^SSLCert/ and s/^/#/;
+	#	/^Listen/ and s/.*/Listen 18443/' conf.d/ssl.conf.sys \
+	#		> conf.d/ssl.conf
+}
+
+[[ "$cmd" == httpd ]] && {
+	do_apache_httpd24
+	exit
+}
+
 [[ "$cmd" == init ]] && {
 	ec2_init
 	exit
@@ -216,26 +253,46 @@ grep "^cdl.username.*$fakeuser" $hgrc && {
 	#      yum can install, but will never update."
 
 	sudo yum -y update			# update to latest OS version
-	sudo yum -y group install "Development Libraries"
+
+	# To browse so-called "package groups", do "yum group list ids".
+# xxx next 3 commands may not have worked
+#    check return status?
+	#sudo yum -y group install "Development Libraries"
 	sudo yum -y group install "Development Tools"   # gcc
-	sudo yum -y group install "Web Server"    # mod_ssl, ExtUtils/MakeMaker
+	sudo yum -y group install "Web Server"    	# ? ExtUtils/MakeMaker
+	sudo yum -y install mod_ssl
+#$ sudo yum -y group install "Development Libraries"
+#Loaded plugins: extras_suggestions, langpacks, priorities, update-motd
+#153 packages excluded due to repository priority protections
+#Warning: group Development Libraries does not exist.
+#Maybe run: yum groups mark install (see man yum)
+#Error: No packages in any requested group available to install or update
+#$ sudo yum -y group install
+#"Development Tools"   # gcc
+#Loaded plugins: extras_suggestions, langpacks, priorities, update-motd
+#153 packages excluded due to repository priority protections
+#Maybe run: yum groups mark install (see man yum)
+#No packages in any requested group available to install or update
+#$ sudo yum -y group install
+#"Web Server"    # mod_ssl, ExtUtils/MakeMaker
+#Loaded plugins: extras_suggestions, langpacks, priorities, update-motd
+#153 packages excluded due to repository priority protections
+#Warning: Group web-server does not have any packages to install.
+#Maybe run: yum groups mark install (see man yum)
+#No packages in any requested group available to install or update
+
 	sudo yum -y install hg
 	sudo yum -y install 'perl(DB_File)' 'perl(BerkeleyDB)'
 	sudo yum -y install 'perl(Data::UUID)' 'perl(Test::More)'
 	sudo yum -y install 'perl(Time::HiRes)'
 
 
-
 	sudo yum -y install 'perl(Log::Log4perl)'
-	# XXX AWS: No package perl(Log::Log4perl) available.
-	#     Error: Nothing to do
 
-	# xxx when system comes up, even partially, crontab is off and spewing
-	#     error messages a little too easily --  how to stop?
+# xxx when system comes up, even partially, crontab is off and spewing
+#     error messages a little too easily --  how to stop?
 
-
-	sudo yum -y install 'perl(XML::LibXML)'
-	sudo yum -y install 'perl(XML::LibXSLT)'
+	sudo yum -y install 'perl(XML::LibXML)' 'perl(XML::LibXSLT)'
 	sudo yum -y install 'perl(App::cpanminus)'
 	sudo yum -y install jq
 
@@ -249,7 +306,7 @@ grep "^cdl.username.*$fakeuser" $hgrc && {
 		exit 1
 	}
 
-	# Trying hypothesis that we don't need these next two yum installs
+	# Try the hypothesis that we don't need these next two yum installs
 	# # XXX should confirm that these next are still needed
 	# # This next installs python's lxml module so that the mdsadmin script
 	# # (that creates DataCite datacenters) can run.
@@ -259,6 +316,7 @@ grep "^cdl.username.*$fakeuser" $hgrc && {
 	# # To use this module, .bashrc sets PYTHONPATH to something like
 	# # PYTHONPATH=$sv/lib64/python2.6/dist-packages
 
+	cd		# go to home directory
 	#hg clone http://hg.cdlib.org/n2t_create
 	hg clone ssh://hg@bitbucket.org/cdl/n2t-admin
 	rm -fr n2t_create	# if it exists the rename below won't work
@@ -276,26 +334,66 @@ grep "^cdl.username.*$fakeuser" $hgrc && {
 #svu new
 #set -u
 
-
 [[ "$cmd" == build ]] && {
-	# XXXX resume script here
-	./make_instance build mongodb_pm httpd n2t > berrs 2>&1
 
+	# XXX watch out that you haven't done svu new already! else this
+	# will build stuff in the next higher svu level
+	svu new || {
+		echo Bailing
+		exit 1
+	}
+	cd ~/n2t_create	|| {	# go to build directory
+		echo Bailing
+		exit 1
+	}
+	# XXXX resume script here
+	#./make_instance build mongodb_pm httpd n2t > berrs 2>&1
+	# NB: ./make_instance requires "svu new", where installs go
+	./make_instance build mongodb_pm n2t > berrs 2>&1 || {
+		echo make_instance error -- bailing
+		svu cur
+		exit 1
+	}
+
+	# now make installed stuff "current" (what was "new" will be "cur")
 	svu rollout	# ok as no users yet; this puts everything of interest
 			# under the 'cur' version, our default logged-in state
+	echo done svu rollout
 
-	### now logout and login again???
+# xxx note that linux1 had libdb 4.7 and linux2 (in /usr/lib64) has
+#     libdb 5.3 -- we MAY need to do db conversion
+	do_apache_httpd24 	# copy and modify system version just
+				# enough to let us start a server
 
-	svu cur		# now make sure that instance is in effect yyy needed?
 
-	mg rs_start		# one-time replica set initialization
+# xxx uncomment
+#	# this now works with Linux2
+#	mg rs_start || {	# one-time replica set initialization
+#		echo Bailing
+#		exit 1
+#	}
+
+
+
+# xxx need to do something to bootstrap this, eg, n2t rollout but before
+#     the first pfx harvest is done, chicken/egg problem
+
+	n2t init
+
+
+
+	apache start
+#config file not found: /apps/n2t/sv/cur/apache2/conf/httpd.conf
+#warning: no apache config file; may be ok for 'stop' or 'status'
+#head: cannot open '/apps/n2t/sv/cur/apache2/conf/httpd.conf' for reading:
+#No such file or directory
 
 	##### !!! you might have to logout and back in for $sv to be correct?
 	#set_crontab go		# takes care of crontab tests
 
 	# XXXX oops: crontab is now set up, but n2t isn't even rolled out!
 
-	pfx init
+	#pfx init
 	pfx hitrnt	# establish prefix stuff, needed for first rollout
 			# yyy this will error out: cd:
 			# /apps/n2t/sv/cv2/apache2/pfx_work/build: No such file
diff --git a/pfx b/pfx
--- a/pfx
+++ b/pfx
@@ -45,6 +45,7 @@ The prefix database is a yaml file built from processed component files.
 A crucial "base" prefix component file lives in and evolves with N2T.net's
 EggNog source. Ingest of components is staged in order to automate entry
 of prefix changes while protecting the system from errors and instability.
+A one-time system initialization of components requires internet access.
 This sub-command lists component locations (if initialized):
 
     $me dirs
@@ -53,10 +54,10 @@ The following sub-commands may be executed in the order listed to update
 the prefixes running on the system.
 
   publish Component
-            To be run on the host (usually prd) where it's maintained, copy
-	    each given Component to a publicly harvestable part of the host's
-	    server, eg, to be harvested from prd to dev and stg. It's of
-	    limited use to publish on servers (eg, stg) that no one harvests.
+            To be run only on the host (usually prd) where the Component file
+	    is maintained, copy it to a publicly harvestable part of the host's
+	    server, eg, to be harvested by dev, stg, or replica prd servers.
+	    It is of no use to publish on servers (eg, stg) no one harvests.
   harvest   Assemble components from external sources (eg, daily via cron)
             -> these will be used for files missing from \$pfx_import dir
             won't overwrite newer files unless -f given
@@ -70,8 +71,10 @@ the prefixes running on the system.
   test      Test prefix lookup and redirect rules (only tests BUILD area)
             Calls (via eggnog's t/z_egg_prefixes_n2t.t) "tested_ok" if all
             tests succeeded. Starts with a completely empty build area.
+	    -> requires built eggnog server
   rollout   Run "install" and restart the N2T Apache server. It's a good idea
             to run "n2t test" now (but see "hitrnt" below).
+	    -> requires built eggnog server
 
 The highest level sub-commands, the first meant to be initiated via crontab.
 
@@ -332,7 +335,7 @@ ark_published=~/sv/cur/apache2/htdocs/e/arks.org
 function pfx_harvest_validate {
 
 	[[ ! -d $pfx_harvest || ! -d $pfx_import ]] && {
-		pfx_init || return
+		pfx_init || return		# yyy needed?
 	}
 	[[ ! -r $pfx_harvest/$pfx_base ]] &&	# yyy update previous stage
 		pfx_base harvest		# from default
@@ -522,7 +525,7 @@ function pfx_base {
 	esac
 
 	# default file with new content default
-	local nfile=$buildout_root/../$source_base_prefixes
+	local nfile=$buildout_root/../../../$source_base_prefixes
 	[[ $# -gt 0 ]] && {
 		nfile=$1
 		shift
@@ -565,7 +568,7 @@ function pfx_base {
 
 function pfx_import {
 	[[ ! -d $pfx_harvest || ! -d $pfx_import ]] && {
-		pfx_init || return
+		pfx_init || return		# yyy needed?
 	}
 	local f
 	for f in $pfx_base ${pfx_sources[@]}
@@ -634,6 +637,14 @@ function pfx_init {
 	}
 	mkdir -p $pfx_harvest || {
 		echo Could not create $pfx_harvest directory. 1>&2
+		return 1
+	}
+	pfx_harvest || {
+		echo Could initialize harvest. 1>&2
+		return 1
+	}
+	pfx_import || {
+		echo Could initialize import 1>&2
 		return 1
 	}
 }
@@ -1326,6 +1337,12 @@ function pfx_stage_pfxcoms {
 # YYY relies on caller defining $pfx_build putting us in the dir it names
 function pfx_validate {
 
+	cd $pfx_build || {
+		echo Could not chdir to $pfx_build. 1>&2
+		return 1
+	}
+	echo "$me process running now in $pfx_build directory"
+
 	local s Nnaans Nshoulders Nebi Npxc	# Numbers of prefixes
 
 	echo - Validating $naanFile
@@ -1379,6 +1396,12 @@ function pfx_validate {
 }
 
 function pfx_combine {
+
+	cd $pfx_build || {
+		echo Could not chdir to $pfx_build. 1>&2
+		return 1
+	}
+	echo "$me process running now in $pfx_build directory"
 
 	# main output
 	cat > $mainout << EOT
@@ -1780,30 +1803,36 @@ EOT
 function pfx_onboard {
 
 	#local source_base_prefixes=$sv/build/eggnog/t/n2t/pfx_base.yaml
-	# yyy separate proc, or call direct?
-	pfx -d $buildout_root prebuild || {	# import from import area
+	# xxx separate proc, or call direct?
+	#pfx -d $buildout_root prebuild || {	# import from import area
+	pfx_prebuild || {	# import from import area
 		echo Error: prebuild failed 1>&2
 		return 1
 	}
-	# yyy separate proc, or call direct?
-	pfx -d $buildout_root base prebuild \
-		$source_base_prefixes || {	# update with latest base file
+	# xxx separate proc, or call direct?
+	#pfx -d $buildout_root base prebuild || {
+	pfx_base prebuild || {
+		#$source_base_prefixes || {	# update with latest base file
 		echo Error: base prebuild failed 1>&2
 		return 1
 	}
-	# yyy separate proc, or call direct?
-	pfx -d $buildout_root updates_ready_in prebuild
+	# xxx separate proc, or call direct?
+	#pfx -d $buildout_root updates_ready_in prebuild
+	pfx_updates_ready_in prebuild
+	# NB: this function's return status will be that of the above command
 }
 
 function pfx_build {
 
-	# yyy separate proc, or call direct?
-	pfx -d $buildout_root validate || {	# validate prefix sources
+	# xxx separate proc, or call direct?
+	#pfx -d $buildout_root validate || {	# validate prefix sources
+	pfx_validate || {	# validate prefix sources
 		echo Error: failed to validate prefixes 1>&2
 		return 1
 	}
-	# yyy separate proc, or call direct?
-	pfx -d $buildout_root combine || {	# create combined prefixes file
+	# xxx separate proc, or call direct?
+	#pfx -d $buildout_root combine || {	# create combined prefixes file
+	pfx_combine || {	# create combined prefixes file
 		echo Error: failed to build prefixes 1>&2
 		return 1
 	}
@@ -2049,6 +2078,7 @@ function pfx_test_rollout_n2t_test {
 	# via command in a "local" and expect to save the return status!
 	echo "+==== trnt: diffs in $diffsfile"
 	local output statsline
+# xxx pfx_<verb>?
 	output=$( pfx test 2>&1 ) || {
 		echo "$output"
 		echo "+==== Error: trnt: pfx test failed"
@@ -2058,6 +2088,7 @@ function pfx_test_rollout_n2t_test {
 	statsline=$( grep '+==== STATS' <<< "$output" )
 	echo "${statsline:-+==== Warning: no STATS line}"
 	echo "$output"
+# xxx pfx_<verb>?
 	pfx rollout 2>&1 || {
 		echo "+==== Error: trnt: pfx rollout failed"
 		return 1
@@ -2120,6 +2151,7 @@ function pfx_cron_hitrnt {
 	local msg=
 	local output=	# NB: local ALWAYS succeeds, so don't initialize
 	# via command in a "local" and expect to save the return status!
+# xxx pfx_<verb>?
 	output+=$( pfx hitrnt 2>&1 )$'\n' || {
 		msg="+==== Error: pfx hitrnt"
 		output+="$msg"
@@ -2144,6 +2176,7 @@ function pfx_cron_hitrnt {
 
 	# else sync to remote host
 	output+="+==== launching \"pfx pfxsync $rhost\""$'\n'
+# xxx pfx_<verb>?
 	output+=$( pfx pfxsync $rhost 2>&1 )$'\n' || {
 		msg="+==== Error: pfx pfxsync $rhost"
 		output+="$msg"
@@ -2160,7 +2193,9 @@ function pfx_cron_hitrnt {
 function pfx_hitrnt {
 
 	echo -n "+==== $( date ) hitrnt: "
-	pfx harvest 2>&1
+# xxx pfx_<verb>?
+	pfx harvest 2>&1		# yyy use internal pfx_harvest, eg,
+				# so we're assure of using correct version?
 	if [[ $? -eq 1 ]]
 	then
 		echo "pfx harvest error; bailing out"
@@ -2178,6 +2213,7 @@ function pfx_hitrnt {
 	then			# proceed with previously aborted update
 		u=$( head -1 $aborted_trnt )
 	else			# proceed if there are any new updates
+# xxx pfx_<verb>?
 		u=$( pfx updates_ready_in harvest ) || {
 					# yyy not checking for real errors
 			echo "$none"		# no updates, caller meant to
@@ -2186,6 +2222,7 @@ function pfx_hitrnt {
 	fi
 	echo "$u"
 
+# xxx pfx_<verb>?
 	pfx import 2>&1 || {
 		echo -e "$u\n+==== import error; bailing out"
 		return 1
@@ -2355,7 +2392,7 @@ pfx_test=$sv/build/eggnog
 #tested_ok_flag=$sv/build/eggnog/td_egnapa/pfx_work/tested_ok
 tested_ok_file=$sv/build/eggnog/td_egnapa/pfx_work/tested_ok
 #tested_ok_file=$pfx_test/td_egnapa/pfx_work/tested_ok
-source_base_prefixes=$sv/build/eggnog/t/n2t/pfx_base.yaml
+#source_base_prefixes=$sv/build/eggnog/t/n2t/pfx_base.yaml
 saveddir=$sv/build/eggnog/pfx_saved
 
 # yyy should put this init stuff in a function and not call it on
@@ -2451,20 +2488,20 @@ publish)
 	exit
 	;;
 validate)
-	cd $pfx_build || {
-		echo Could not chdir to $pfx_build. 1>&2
-		exit 1
-	}
-	echo "$me process running now in $pfx_build directory"
+	#cd $pfx_build || {
+	#	echo Could not chdir to $pfx_build. 1>&2
+	#	exit 1
+	#}
+	#echo "$me process running now in $pfx_build directory"
 	pfx_prebuild "$@" && pfx_validate "$@"		# yyy args unused
 	exit
 	;;
 combine)
-	cd $pfx_build || {
-		echo Could not chdir to $pfx_build. 1>&2
-		exit 1
-	}
-	echo "$me process running now in $pfx_build directory"
+	#cd $pfx_build || {
+	#	echo Could not chdir to $pfx_build. 1>&2
+	#	exit 1
+	#}
+	#echo "$me process running now in $pfx_build directory"
 	pfx_combine "$@"	# yyy args unused
 	exit
 	;;
@@ -2488,7 +2525,8 @@ tested_ok)
 	exit
 	;;
 init)
-	pfx_init "$@"
+	echo Initialized	# yyy implicitly, else we wouldn't get this far
+	#pfx_init "$@"
 	exit
 	;;
 find)
