improve logic when no updates present, fix whitespace

diff --git a/pfx b/pfx
--- a/pfx
+++ b/pfx
@@ -60,6 +60,8 @@ pubregARK=https://n2t.net/ark:/13030/c7xk84q2j
 requestURL=https://n2t.net/e/prefix_request
 n2tregout=n2t_prefixes.yaml
 harvest_log=~/logs/pfx_harvest_log
+none='(none)'
+
 function temper {
 	date '+%Y.%m.%d_%H.%M.%S/%z'
 }
@@ -1285,6 +1287,7 @@ function pfx_stage_pfxcoms {
 	return 0
 }
 
+# YYY make each of these return a number for stats
 # YYY relies on caller defining $pfx_build putting us in the dir it names
 function pfx_validate {
 
@@ -1939,7 +1942,7 @@ function pfx_test_rollout_n2t_test {
 			echo -ne '+++ ';
 			ls -l $new | sed s/^..........................//;
 			diff --ignore-space-change $old $new; 
-		) >  $diffsfile
+		) > $diffsfile
 		# want much quieter diff, eg, only want text changes,
 		# not the line position of every text change
 	done
@@ -1947,7 +1950,7 @@ function pfx_test_rollout_n2t_test {
 
 	local output=	# NB: local ALWAYS succeeds, so don't initialize
 	# via command in a "local" and expect to save the return status!
-	echo -e "+==== diffs in $diffsfile\n\n"
+	echo "+==== diffs in $diffsfile"
 	pfx test 2>&1 || {
 		echo "+==== Error: pfx test failed"
 		return 1
@@ -1971,32 +1974,41 @@ function pfx_cron_hitrnt {
 
 	local mailto=${1:-$pfxadmin}
 	local rhost=${2:-}
-	local msg=
+	local msg
 	local output=	# NB: local ALWAYS succeeds, so don't initialize
 	# via command in a "local" and expect to save the return status!
-	output+=$( pfx hitrnt 2>&1 ) || {
+	output+=$( pfx hitrnt 2>&1 )$'\n' || {
 		msg="+==== Error: pfx hitrnt"
 		output+="$msg"
 		echo "$output" >> $harvest_log
 		mail -s "$msg" $mailto <<< "$output"
 		return 1
 	}
-	[[ ! "$rhost" ]] && {		# if no 2nd arg present
-		mail -s "ok: cron hitrnt" $mailto <<< "$output"
+	msg=
+	if [[ ! "$rhost" ]]
+	then
+		msg="no pfxsync"
+	elif [[ "$output" =~ "$none" ]]
+	then
+		msg="nothing to update"
+	fi
+	# if no 2nd arg present or if no updates were detected
+	[[ "$msg" ]] && {
+		echo "$output" >> $harvest_log
+		mail -s "ok: cron hitrnt, $msg" $mailto <<< "$output"
 		return 0			# done
 	}
 
 	# else sync to remote host
-	output+="+==== launching \"pfx_pfxsync $rhost $mailto\""
-	#echo "$msg" >> $harvest_log
-	output+=$( pfx_pfxsync $rhost 2>&1 ) || {
+	output+="+==== launching \"pfx_pfxsync $rhost $mailto\"\n"
+	output+=$( pfx_pfxsync $rhost 2>&1 )$'\n' || {
 		msg="+==== Error: pfx pfxsync $rhost"
 		output+="$msg"
 		echo "$output" >> $harvest_log
 		mail -s "$msg" $mailto <<< "$output"
 		return 1
 	}
-	mail -s "ok: cron pfxsync and hitrnt" $mailto <<< "$output"
+	mail -s "ok: cron hitrnt $rhost" $mailto <<< "$output"
 	return
 }
 
@@ -2006,14 +2018,14 @@ function pfx_hitrnt {
 
 	#local mailto=${1:-$pfxadmin}
 	#local rhost=${2:-}
-	echo -n +==== `date`
+	echo -n "+==== $( date ) cron hitrnt: "
 	pfx harvest 2>&1
 	if [[ $? -eq 1 ]]
 	then
-		echo ", pfx harvest error; bailing out"
+		echo "pfx harvest error; bailing out"
 		return 1
 	fi
-	echo -n , 'harvested, updates ready: '
+	echo -n "harvested, updates ready: "
 
 	# Semaphore file $aborted_update, of form
 	#   line  1. <list of space-separated names of changed files>
@@ -2027,12 +2039,12 @@ function pfx_hitrnt {
 	else			# proceed if there are any new updates
 		u=$( pfx updates_ready_in harvest ) || {
 					# yyy not checking for real errors
-			echo '(none)'		# no updates, caller meant to
+			echo "$none"		# no updates, caller meant to
 			return 0		# see 0 as "keep quiet"
 		}
 	fi
-
 	echo "$u; processing updates"
+
 	pfx import 2>&1 || {
 		echo "$u"
 		echo "+==== import error; bailing out"
